GET localhost:8080/api/v1/tasks

###
POST localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "title": "watch some television",
  "description" : "television is bad for you !!!"
}
###
POST localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "title": "take out the trash",
  "description" : "trash needs to be pulled to the road every monday"
}
###

DELETE localhost:8080/api/v1/tasks/1


